name: Initiate tests on '-installer' repositories

on:
  workflow_dispatch:

jobs:

  github-notify:
    strategy:
      fail-fast: true
      matrix:
        # repository
        #    [HOST/]OWNER/REPO format
        repository: ["diskuv/dkml-installer-ocaml"]
    runs-on: ubuntu-latest
    steps:
      - name: POST workflow dispatch
        env:
          REPOSITORY: ${{ matrix.repository }}
          GITHUB_TOKEN: ${{ secrets.TRIGGER_DKML_INSTALLER_OCAML }}
        run: |
          set -x && gh workflow --repo "${REPOSITORY}" run package.yml -f dkml-component-opam=${GITHUB_SHA}
