name: Test and Notify
on:
  push:
    branches:
      # Any commit to the main branch
      - "main"
    tags:
      # Any push to a tag that starts with 'v'
      - v*

jobs:
  # Notify Installers on GitHub
  github-notify:
    if: false # DISABLED UNTIL WE HAVE A NEED TO KICK OFF dkml-installer-ocaml    
    strategy:
      fail-fast: true
      matrix:
        # repository
        #    [HOST/]OWNER/REPO format
        repository: ["diskuv/dkml-installer-ocaml"]
    runs-on: ubuntu-latest
    steps:
      - name: POST workflow dispatch
        env:
          REPOSITORY: ${{ matrix.repository }}
          GITHUB_TOKEN: ${{ secrets.TRIGGER_DKML_INSTALLER_OCAML }}
        run: |
          set -x && gh workflow --repo "${REPOSITORY}" run package.yml -f dkml-component-opam=${GITHUB_SHA} -f populate-cache=false
